"""
POLARIS-EMS — Digital Twin Computational Simulation Engine
SIH26061: Polar Energy Management & Resilience System

The authoritative stateful computational Energy Digital Twin for polar research stations.
Executes forward state transitions under BASELINE_SIMULATION_DISPATCH:
Predict (ML) -> Simulate (Twin) -> Optimize (Phase 6) -> Protect -> Preserve

All states maintain strict field-level provenance and exact energy conservation.
"""

from typing import Dict, List, Optional, Any, Literal, Tuple
from dataclasses import dataclass, asdict
from pathlib import Path
import pandas as pd
import numpy as np

from backend.twin.state import (
    TwinState,
    EnvironmentState,
    ThermalState,
    LoadState,
    SolarState,
    WindState,
    BatteryState,
    DieselState,
    FuelState,
    ResupplyState,
    OperationalState,
    ConstraintEvaluation,
    ResilienceState
)
from backend.twin.safety_thresholds import SafetyThresholdRegistry
from backend.twin.thermal_engine import ThermalEngine
from backend.twin.load_engine import LoadEngine
from backend.twin.solar_engine import SolarEngine
from backend.twin.wind_engine import WindEngine
from backend.twin.battery_engine import BatteryEngine
from backend.twin.diesel_fuel_engine import DieselFuelEngine
from backend.twin.power_balance import PowerBalanceEngine, DispatchResult
from backend.twin.constraints import ConstraintEvaluator
from backend.twin.resilience import ResilienceEngine
from backend.twin.forecast_adapter import TwinInputStep
from backend.data.station_profiles.loader import StationProfileRegistry, StationProfile


@dataclass
class TwinTrajectory:
    """Multi-step time series trajectory generated by the Digital Twin."""
    station_id: str
    mode: str
    states: List[TwinState]
    summary: Dict[str, Any]

    def to_dataframe(self) -> pd.DataFrame:
        """Converts trajectory states into an analysis-ready DataFrame."""
        rows = []
        for s in self.states:
            res = s.resilience
            rows.append({
                "station_id": s.station_id,
                "timestamp": s.timestamp,
                "ambient_temp_c": s.environment.temperature_c,
                "wind_speed_m_per_s": s.environment.wind_speed_m_per_s,
                "ghi_w_per_m2": s.environment.ghi_w_per_m2,
                "indoor_temp_c": s.thermal.indoor_temp_c,
                "thermal_loss_kw": s.thermal.thermal_loss_kw,
                "total_load_kw": s.loads.total_load_kw,
                "critical_load_kw": s.loads.critical_load_kw,
                "served_load_kw": s.loads.served_load_kw,
                "unserved_load_kw": s.loads.unserved_load_kw,
                "served_critical_kw": s.loads.served_critical_kw,
                "unserved_critical_kw": s.loads.unserved_critical_kw,
                "solar_available_kw": s.solar.solar_available_kw,
                "solar_generation_kw": s.solar.solar_generation_kw,
                "solar_curtailed_kw": s.solar.solar_curtailed_kw,
                "wind_available_kw": s.wind.wind_available_kw,
                "wind_generation_kw": s.wind.wind_generation_kw,
                "wind_curtailed_kw": s.wind.wind_curtailed_kw,
                "battery_charge_kw": s.battery.charge_power_kw,
                "battery_discharge_kw": s.battery.discharge_power_kw,
                "battery_soc_pct": s.battery.soc_pct,
                "battery_usable_kwh": s.battery.usable_capacity_kwh,
                "diesel_power_kw": s.diesel.generator_power_kw,
                "diesel_status": s.diesel.generator_status,
                "fuel_consumption_l_per_h": s.diesel.fuel_consumption_l_per_h,
                "fuel_remaining_l": s.fuel.fuel_remaining_l,
                "fuel_consumed_l": s.fuel.fuel_consumed_l,
                "days_of_fuel_remaining": s.fuel.days_of_fuel_remaining,
                "nameplate_reserve_kw": res.nameplate_reserve_kw if res else 0.0,
                "dependable_reserve_kw": res.dependable_reserve_kw if res else 0.0,
                "dependable_reserve_pct": res.dependable_reserve_pct if res else 0.0,
                "fuel_constrained_reserve_kw": res.fuel_constrained_reserve_kw if res else 0.0,
                "critical_load_survival_status": res.critical_load_survival_status if res else "UNKNOWN",
                "continuity_horizon_hours": res.continuity_horizon_hours if res else 0.0,
                "threat_state": res.threat_state if res else "UNKNOWN",
                "dispatch_policy": s.dispatch_policy,
                "provenance": s.provenance
            })
        return pd.DataFrame(rows)


class TwinEngine:
    """The central computational Energy Digital Twin simulator for Polaris-EMS."""

    def __init__(
        self,
        station_id: str,
        profile: Optional[StationProfile] = None,
        safety_registry: Optional[SafetyThresholdRegistry] = None
    ):
        self.station_id = station_id.upper()
        if profile is None:
            registry = StationProfileRegistry()
            profile = registry.get(self.station_id)
        self.profile = profile

        self.safety_registry = safety_registry or SafetyThresholdRegistry()
        self.thermal_engine = ThermalEngine(self.safety_registry)
        self.load_engine = LoadEngine(self.profile)
        self.solar_engine = SolarEngine(self.profile)
        self.wind_engine = WindEngine(self.profile)
        self.battery_engine = BatteryEngine(self.profile)
        self.diesel_fuel_engine = DieselFuelEngine(self.profile)
        self.power_balance = PowerBalanceEngine()
        self.constraint_evaluator = ConstraintEvaluator(self.safety_registry)
        self.resilience_engine = ResilienceEngine(self.profile, self.safety_registry)

    def initialize_twin(
        self,
        timestamp: str,
        initial_telemetry: Optional[Dict[str, Any]] = None
    ) -> TwinState:
        """Initializes a physically consistent initial TwinState."""
        telem = initial_telemetry or {}

        # Environment
        amb_temp = float(telem.get("ambient_temp_c", -15.0))
        wind_spd = float(telem.get("wind_speed_m_per_s", 8.0))
        ghi = float(telem.get("ghi_w_per_m2", 0.0))
        env_state = EnvironmentState(
            ambient_temperature_c=amb_temp,
            wind_speed_ms=wind_spd,
            irradiance_wm2=ghi,
            solar_elevation_deg=15.0 if ghi > 0 else 0.0,
            provenance="OBSERVED" if initial_telemetry else "CONFIGURED"
        )

        # Operational
        op_state = OperationalState(
            occupancy_factor=float(telem.get("occupancy_factor", 1.0)),
            research_activity=float(telem.get("research_activity", 1.0)),
            communication_activity=float(telem.get("communication_activity", 1.0)),
            maintenance_active=float(telem.get("maintenance_active", 0.0)),
            flexible_load_schedule=float(telem.get("flexible_load_schedule", 0.0)),
            provenance="CONFIGURED"
        )

        # Thermal
        indoor_temp = float(telem.get("indoor_temp_c", self.profile.thermal.indoor_target_temp_c))
        therm_state = ThermalState(
            indoor_temperature_c=indoor_temp,
            thermal_setpoint_c=self.profile.thermal.indoor_target_temp_c,
            indoor_min_safe_temp_c=self.profile.thermal.indoor_min_safe_temp_c,
            thermal_loss_kw=0.0,
            building_ua_kw_per_k=self.profile.thermal.building_ua_kw_per_k,
            thermal_capacitance_kwh_per_k=self.profile.thermal.thermal_capacitance_kwh_per_k,
            ventilation_loss_coeff=self.profile.thermal.ventilation_loss_coeff,
            internal_heat_gain_kw=self.profile.thermal.internal_heat_gain_kw,
            chp_heat_recovered_kw=0.0,
            provenance="CONFIGURED"
        )
        _, init_loss = self.thermal_engine.calculate_heating_demand(therm_state, amb_temp)
        therm_state.thermal_loss_kw = init_loss

        # Load
        req_heating, _ = self.thermal_engine.calculate_heating_demand(therm_state, amb_temp)
        init_load = float(telem.get("total_load_kw", 40.0))
        load_state = self.load_engine.calculate_subloads(
            thermal_load_kw=req_heating,
            op_state=op_state,
            effective_temp_c=amb_temp,
            forecast_total_load_kw=init_load
        )
        load_state.served_load_kw = load_state.total_load_kw
        load_state.served_critical_kw = load_state.critical_load_kw

        # Solar & Wind
        solar_state = self.solar_engine.step(ghi, amb_temp, env_state.solar_elevation_deg)
        wind_state = self.wind_engine.step(wind_spd)

        # Battery
        soc = float(telem.get("soc_pct", self.profile.electrical.battery_nominal_soc))
        derate, usable_kwh = self.battery_engine.compute_derating(amb_temp)
        bat_state = BatteryState(
            soc_pct=soc,
            energy_kwh=round(soc * usable_kwh, 2),
            charge_kw=0.0,
            discharge_kw=0.0,
            capacity_kwh=float(self.profile.electrical.battery_capacity_kwh),
            usable_capacity_kwh=usable_kwh,
            charge_efficiency=round(np.sqrt(self.profile.electrical.battery_roundtrip_efficiency), 4),
            discharge_efficiency=round(np.sqrt(self.profile.electrical.battery_roundtrip_efficiency), 4),
            temperature_derating=derate,
            soc_min=self.profile.electrical.battery_min_soc,
            soc_max=self.profile.electrical.battery_max_soc,
            provenance="CONFIGURED"
        )

        # Diesel & Fuel
        p_max = float(self.profile.electrical.diesel_generator_kw_rated)
        min_load = float(self.profile.electrical.diesel_min_loading_pct)
        diesel_state = DieselState(
            generator_status=str(telem.get("generator_status", "STANDBY")),
            online_count=1 if telem.get("generator_status") == "ONLINE" else 0,
            generator_power_kw=float(telem.get("diesel_power_kw", 0.0)),
            generator_min_power_kw=round(p_max * min_load, 2),
            generator_max_power_kw=round(p_max, 2),
            fuel_consumption_l_per_h=0.0,
            cumulative_runtime_h=0.0,
            provenance="CONFIGURED"
        )

        init_fuel = float(telem.get("fuel_remaining_l", self.profile.fuel.initial_fuel_liters))
        fuel_state = FuelState(
            fuel_remaining_l=init_fuel,
            fuel_initial_l=self.profile.fuel.initial_fuel_liters,
            fuel_consumed_l=0.0,
            fuel_reserve_l=self.profile.fuel.critical_fuel_reserve_liters,
            fuel_capacity_l=self.profile.fuel.storage_capacity_liters,
            days_of_fuel_remaining=round(init_fuel / 350.0, 1),
            provenance="CONFIGURED"
        )

        resupply_state = ResupplyState(
            next_resupply_date="2026-12-15",
            resupply_window_days=self.profile.default_resupply_window_days,
            resupply_event_active=False,
            fuel_delivered_liters=0.0,
            provenance="CONFIGURED"
        )

        # Initial electrical dispatch balance
        dispatch = self.power_balance.solve_baseline_dispatch(
            requested_load_kw=load_state.total_load_kw,
            critical_load_kw=load_state.critical_load_kw,
            solar_available_kw=solar_state.solar_available_kw,
            wind_available_kw=wind_state.wind_available_kw,
            max_battery_charge_kw=self.profile.electrical.battery_max_charge_kw,
            max_battery_discharge_kw=self.profile.electrical.battery_max_discharge_kw,
            max_diesel_power_kw=p_max,
            min_diesel_power_kw=round(p_max * min_load, 2)
        )
        load_state.served_load_kw = dispatch.served_load_kw
        load_state.unserved_load_kw = dispatch.unserved_load_kw
        load_state.served_critical_kw = dispatch.served_critical_kw
        load_state.unserved_critical_kw = dispatch.unserved_critical_kw
        solar_state.solar_generation_kw = dispatch.solar_generation_kw
        solar_state.solar_curtailed_kw = max(0.0, solar_state.solar_available_kw - dispatch.solar_generation_kw)
        wind_state.wind_generation_kw = dispatch.wind_generation_kw
        wind_state.wind_curtailed_kw = max(0.0, wind_state.wind_available_kw - dispatch.wind_generation_kw)
        bat_state.charge_kw = dispatch.battery_charge_kw
        bat_state.discharge_kw = dispatch.battery_discharge_kw
        if "generator_status" not in telem and "diesel_power_kw" not in telem:
            diesel_state.generator_power_kw = dispatch.diesel_power_kw
            diesel_state.generator_status = "ONLINE" if dispatch.diesel_power_kw > 0.01 else "STANDBY"
            diesel_state.online_count = 1 if dispatch.diesel_power_kw > 0.01 else 0
            diesel_state.fuel_consumption_l_per_h = self.diesel_fuel_engine.calculate_fuel_consumption(dispatch.diesel_power_kw, 1.0)

        state = TwinState(
            station_id=self.station_id,
            timestamp=timestamp,
            environment=env_state,
            thermal=therm_state,
            loads=load_state,
            solar=solar_state,
            wind=wind_state,
            battery=bat_state,
            diesel=diesel_state,
            fuel=fuel_state,
            resupply=resupply_state,
            operational=op_state,
            dispatch_policy="BASELINE_SIMULATION_DISPATCH",
            provenance="CONFIGURED"
        )

        state.constraints = self.constraint_evaluator.evaluate_all(state)
        state.resilience = self.resilience_engine.evaluate_resilience(state, dt_hours=1.0)
        return state

    def step(
        self,
        current_state: TwinState,
        input_step: TwinInputStep,
        dt_hours: float = 1.0
    ) -> TwinState:
        """
        Executes a single forward state transition under BASELINE_SIMULATION_DISPATCH.
        """
        amb_temp = input_step.ambient_temp_c
        wind_spd = input_step.wind_speed_m_per_s
        ghi = input_step.ghi_w_per_m2

        # 1. Environment Update
        env_state = EnvironmentState(
            ambient_temperature_c=amb_temp,
            wind_speed_ms=wind_spd,
            irradiance_wm2=ghi,
            solar_elevation_deg=15.0 if ghi > 0 else 0.0,
            provenance="FORECAST"
        )

        # 2. Thermal Heating Requirement
        req_heating_kw, _ = self.thermal_engine.calculate_heating_demand(
            current_state.thermal, amb_temp
        )

        # 3. Load Subsystem Update
        load_state = self.load_engine.calculate_subloads(
            thermal_load_kw=req_heating_kw,
            op_state=current_state.operational,
            effective_temp_c=amb_temp,
            forecast_total_load_kw=input_step.load_kw
        )
        p_load_req = load_state.total_load_kw
        p_crit_req = load_state.critical_load_kw

        # 4. Renewable Potential Calculation
        solar_candidate = self.solar_engine.step(
            irradiance_wm2=ghi,
            ambient_temp_c=amb_temp,
            solar_elevation_deg=env_state.solar_elevation_deg,
            forecast_solar_kw=input_step.solar_kw if input_step.solar_kw > 0.0 else None
        )
        p_solar_avail = solar_candidate.solar_available_kw

        wind_candidate = self.wind_engine.step(
            wind_speed_ms=wind_spd,
            forecast_wind_kw=input_step.wind_kw if input_step.wind_kw > 0.0 else None
        )
        p_wind_avail = wind_candidate.wind_available_kw

        # 5. Dispatch Limits
        max_chg_kw, max_dis_kw = self.battery_engine.get_dispatch_limits(
            current_state.battery, amb_temp, dt_hours
        )

        p_diesel_max = current_state.diesel.generator_max_power_kw
        p_diesel_min = current_state.diesel.generator_min_power_kw
        if current_state.fuel.fuel_remaining_l <= 0.01 or current_state.diesel.generator_status == "FAULT":
            p_diesel_max = 0.0
            p_diesel_min = 0.0

        # 6. Electrical Power Balance under BASELINE_SIMULATION_DISPATCH
        dispatch = self.power_balance.solve_baseline_dispatch(
            requested_load_kw=p_load_req,
            critical_load_kw=p_crit_req,
            solar_available_kw=p_solar_avail,
            wind_available_kw=p_wind_avail,
            max_battery_charge_kw=max_chg_kw,
            max_battery_discharge_kw=max_dis_kw,
            max_diesel_power_kw=p_diesel_max,
            min_diesel_power_kw=p_diesel_min
        )

        # 7. Subsystem State Transitions
        # Loads
        load_state.served_load_kw = dispatch.served_load_kw
        load_state.unserved_load_kw = dispatch.unserved_load_kw
        load_state.served_critical_kw = dispatch.served_critical_kw
        load_state.unserved_critical_kw = dispatch.unserved_critical_kw
        load_state.provenance = "SIMULATED"

        # Solar & Wind with curtailment
        solar_curt = max(0.0, p_solar_avail - dispatch.solar_generation_kw)
        solar_state = self.solar_engine.step(
            irradiance_wm2=ghi,
            ambient_temp_c=amb_temp,
            solar_elevation_deg=env_state.solar_elevation_deg,
            curtailed_kw=solar_curt,
            forecast_solar_kw=input_step.solar_kw if input_step.solar_kw > 0.0 else None
        )

        wind_curt = max(0.0, p_wind_avail - dispatch.wind_generation_kw)
        wind_state = self.wind_engine.step(
            wind_speed_ms=wind_spd,
            curtailed_kw=wind_curt,
            forecast_wind_kw=input_step.wind_kw if input_step.wind_kw > 0.0 else None
        )

        # Battery
        battery_state = self.battery_engine.step(
            current_state=current_state.battery,
            ambient_temp_c=amb_temp,
            charge_kw=dispatch.battery_charge_kw,
            discharge_kw=dispatch.battery_discharge_kw,
            dt_hours=dt_hours
        )

        # Diesel & Fuel
        diesel_state, fuel_state = self.diesel_fuel_engine.step(
            diesel_state=current_state.diesel,
            fuel_state=current_state.fuel,
            requested_gen_power_kw=dispatch.diesel_power_kw,
            resupply_state=current_state.resupply,
            dt_hours=dt_hours
        )

        # Thermal State
        load_fraction_served = dispatch.served_load_kw / max(0.01, p_load_req)
        actual_heating_kw = req_heating_kw * load_fraction_served
        thermal_state = self.thermal_engine.step(
            current_state=current_state.thermal,
            ambient_temp_c=amb_temp,
            actual_heating_power_kw=actual_heating_kw,
            dt_hours=dt_hours
        )
        temp_rate = (thermal_state.indoor_temp_c - current_state.thermal.indoor_temp_c) / max(0.01, dt_hours)

        # 8. Assemble Next State
        next_state = TwinState(
            station_id=self.station_id,
            timestamp=input_step.timestamp,
            environment=env_state,
            thermal=thermal_state,
            loads=load_state,
            solar=solar_state,
            wind=wind_state,
            battery=battery_state,
            diesel=diesel_state,
            fuel=fuel_state,
            resupply=current_state.resupply,
            operational=current_state.operational,
            dispatch_policy="BASELINE_SIMULATION_DISPATCH",
            provenance="SIMULATED"
        )

        # 9. Evaluate Constraints & Resilience
        next_state.constraints = self.constraint_evaluator.evaluate_all(next_state)
        next_state.resilience = self.resilience_engine.evaluate_resilience(
            next_state, dt_hours=dt_hours, temp_rate_c_per_h=temp_rate
        )

        return next_state

    def simulate(
        self,
        initial_state: TwinState,
        trajectory_steps: List[TwinInputStep],
        dt_hours: float = 1.0
    ) -> TwinTrajectory:
        """
        Executes a multi-timestep trajectory forward simulation.
        """
        states: List[TwinState] = []
        current = initial_state

        total_unserved_kwh = 0.0
        total_critical_unserved_kwh = 0.0
        total_curtailed_kwh = 0.0
        total_diesel_generated_kwh = 0.0
        total_fuel_burned_l = 0.0
        threat_state_counts = {"SAFE": 0, "AT_RISK": 0, "THREATENED": 0, "CRITICAL": 0}

        mode = trajectory_steps[0].mode if trajectory_steps else "EXPECTED"

        for step_input in trajectory_steps:
            current = self.step(current, step_input, dt_hours=dt_hours)
            states.append(current)

            total_unserved_kwh += current.loads.unserved_load_kw * dt_hours
            total_critical_unserved_kwh += current.loads.unserved_critical_kw * dt_hours
            total_curtailed_kwh += (current.solar.solar_curtailed_kw + current.wind.wind_curtailed_kw) * dt_hours
            total_diesel_generated_kwh += current.diesel.generator_power_kw * dt_hours
            total_fuel_burned_l += current.diesel.fuel_consumption_l_per_h * dt_hours

            if current.resilience:
                ts = current.resilience.threat_state
                threat_state_counts[ts] = threat_state_counts.get(ts, 0) + 1

        summary = {
            "station_id": self.station_id,
            "mode": mode,
            "steps": len(states),
            "duration_hours": len(states) * dt_hours,
            "total_unserved_kwh": round(total_unserved_kwh, 2),
            "total_critical_unserved_kwh": round(total_critical_unserved_kwh, 2),
            "total_curtailed_kwh": round(total_curtailed_kwh, 2),
            "total_diesel_generated_kwh": round(total_diesel_generated_kwh, 2),
            "total_fuel_burned_liters": round(total_fuel_burned_l, 2),
            "final_fuel_remaining_liters": current.fuel.fuel_remaining_l,
            "final_battery_soc": round(current.battery.soc_pct, 4),
            "final_indoor_temp_c": round(current.thermal.indoor_temp_c, 2),
            "threat_state_distribution": threat_state_counts,
            "critical_survival": "PASSED" if total_critical_unserved_kwh < 1e-4 else "FAILED"
        }

        return TwinTrajectory(
            station_id=self.station_id,
            mode=mode,
            states=states,
            summary=summary
        )

    def step_with_dispatch(
        self,
        current_state: TwinState,
        input_step: TwinInputStep,
        dispatch: DispatchResult,
        dispatch_policy: str = "OPTIMIZED_DISPATCH",
        dt_hours: float = 1.0
    ) -> TwinState:
        """
        Executes a single forward state transition using candidate dispatch decisions.
        Enforces identical physical equations (battery electrochemistry, thermal loss,
        fuel burn) as baseline simulation to validate physical feasibility.
        """
        amb_temp = input_step.ambient_temp_c
        wind_spd = input_step.wind_speed_m_per_s
        ghi = input_step.ghi_w_per_m2

        # 1. Environment Update
        env_state = EnvironmentState(
            ambient_temperature_c=amb_temp,
            wind_speed_ms=wind_spd,
            irradiance_wm2=ghi,
            solar_elevation_deg=15.0 if ghi > 0 else 0.0,
            provenance="FORECAST"
        )

        # 2. Thermal Heating Requirement
        req_heating_kw, _ = self.thermal_engine.calculate_heating_demand(
            current_state.thermal, amb_temp
        )

        # 3. Load Subsystem Update
        load_state = self.load_engine.calculate_subloads(
            thermal_load_kw=req_heating_kw,
            op_state=current_state.operational,
            effective_temp_c=amb_temp,
            forecast_total_load_kw=input_step.load_kw
        )
        p_load_req = load_state.total_load_kw

        # Apply candidate dispatch load service
        load_state.served_load_kw = dispatch.served_load_kw
        load_state.unserved_load_kw = dispatch.unserved_load_kw
        load_state.served_critical_kw = dispatch.served_critical_kw
        load_state.unserved_critical_kw = dispatch.unserved_critical_kw
        load_state.provenance = "SIMULATED"

        # 4. Renewable Curtailment
        solar_cand = self.solar_engine.step(
            irradiance_wm2=ghi,
            ambient_temp_c=amb_temp,
            solar_elevation_deg=env_state.solar_elevation_deg,
            forecast_solar_kw=input_step.solar_kw if input_step.solar_kw > 0.0 else None
        )
        solar_curt = max(0.0, solar_cand.solar_available_kw - dispatch.solar_generation_kw)
        solar_state = self.solar_engine.step(
            irradiance_wm2=ghi,
            ambient_temp_c=amb_temp,
            solar_elevation_deg=env_state.solar_elevation_deg,
            curtailed_kw=solar_curt,
            forecast_solar_kw=input_step.solar_kw if input_step.solar_kw > 0.0 else None
        )

        wind_cand = self.wind_engine.step(
            wind_speed_ms=wind_spd,
            forecast_wind_kw=input_step.wind_kw if input_step.wind_kw > 0.0 else None
        )
        wind_curt = max(0.0, wind_cand.wind_available_kw - dispatch.wind_generation_kw)
        wind_state = self.wind_engine.step(
            wind_speed_ms=wind_spd,
            curtailed_kw=wind_curt,
            forecast_wind_kw=input_step.wind_kw if input_step.wind_kw > 0.0 else None
        )

        # 5. Battery Dynamics
        battery_state = self.battery_engine.step(
            current_state=current_state.battery,
            ambient_temp_c=amb_temp,
            charge_kw=dispatch.battery_charge_kw,
            discharge_kw=dispatch.battery_discharge_kw,
            dt_hours=dt_hours
        )

        # 6. Diesel Generator & Fuel Depletion
        diesel_state, fuel_state = self.diesel_fuel_engine.step(
            diesel_state=current_state.diesel,
            fuel_state=current_state.fuel,
            requested_gen_power_kw=dispatch.diesel_power_kw,
            resupply_state=current_state.resupply,
            dt_hours=dt_hours
        )

        # 7. Thermal State
        load_fraction_served = dispatch.served_load_kw / max(0.01, p_load_req)
        actual_heating_kw = req_heating_kw * load_fraction_served
        thermal_state = self.thermal_engine.step(
            current_state=current_state.thermal,
            ambient_temp_c=amb_temp,
            actual_heating_power_kw=actual_heating_kw,
            dt_hours=dt_hours
        )
        temp_rate = (thermal_state.indoor_temp_c - current_state.thermal.indoor_temp_c) / max(0.01, dt_hours)

        # 8. Assemble Next State
        next_state = TwinState(
            station_id=self.station_id,
            timestamp=input_step.timestamp,
            environment=env_state,
            thermal=thermal_state,
            loads=load_state,
            solar=solar_state,
            wind=wind_state,
            battery=battery_state,
            diesel=diesel_state,
            fuel=fuel_state,
            resupply=current_state.resupply,
            operational=current_state.operational,
            dispatch_policy=dispatch_policy,
            provenance="SIMULATED"
        )

        # 9. Evaluate Constraints & Resilience
        next_state.constraints = self.constraint_evaluator.evaluate_all(next_state)
        next_state.resilience = self.resilience_engine.evaluate_resilience(
            next_state, dt_hours=dt_hours, temp_rate_c_per_h=temp_rate
        )

        return next_state

    def simulate_dispatch(
        self,
        initial_state: TwinState,
        trajectory_steps: List[TwinInputStep],
        dispatch_schedule: List[DispatchResult],
        dispatch_policy: str = "OPTIMIZED_DISPATCH",
        dt_hours: float = 1.0
    ) -> Tuple[TwinTrajectory, bool, List[str]]:
        """
        Executes a multi-timestep replay forward simulation using candidate dispatch decisions.
        Validates all 10 physical constraints and energy balance (|err| < 1e-4 kW).
        Returns:
            (trajectory, is_valid, validation_messages)
        """
        states: List[TwinState] = []
        validation_messages: List[str] = []
        is_valid = True
        current = initial_state

        total_unserved_kwh = 0.0
        total_critical_unserved_kwh = 0.0
        total_curtailed_kwh = 0.0
        total_diesel_generated_kwh = 0.0
        total_fuel_burned_l = 0.0
        threat_state_counts = {"SAFE": 0, "AT_RISK": 0, "THREATENED": 0, "CRITICAL": 0}

        mode = trajectory_steps[0].mode if trajectory_steps else "EXPECTED"

        for t, (step_input, dispatch) in enumerate(zip(trajectory_steps, dispatch_schedule)):
            current = self.step_with_dispatch(
                current_state=current,
                input_step=step_input,
                dispatch=dispatch,
                dispatch_policy=dispatch_policy,
                dt_hours=dt_hours
            )
            states.append(current)

            # Check electrical power balance error
            sources = (dispatch.solar_generation_kw + dispatch.wind_generation_kw +
                       dispatch.diesel_power_kw + dispatch.battery_discharge_kw)
            sinks = dispatch.served_load_kw + dispatch.battery_charge_kw
            pb_err = abs(sources - sinks)
            if pb_err > 0.02:
                is_valid = False
                validation_messages.append(
                    f"Step {t+1} ({step_input.timestamp}): Power balance violation |err| = {pb_err:.4f} kW"
                )

            # Check constraint evaluator for VIOLATED status
            for c_eval in current.constraints:
                if c_eval.status == "VIOLATED":
                    # Non-critical unserved energy is an operational shedding choice, but
                    # battery SOC breaches, negative fuel, or generator overpower are physical violations
                    if c_eval.constraint_name in (
                        "diesel_generator_max_capacity",
                        "battery_soc_minimum",
                        "battery_soc_maximum",
                        "battery_charge_rate_limit",
                        "battery_discharge_rate_limit",
                        "fuel_storage_capacity",
                        "electrical_power_balance"
                    ):
                        is_valid = False
                        validation_messages.append(
                            f"Step {t+1} ({step_input.timestamp}): Hard physical constraint '{c_eval.constraint_name}' VIOLATED (magnitude={c_eval.violation_magnitude:.2f})"
                        )

            total_unserved_kwh += current.loads.unserved_load_kw * dt_hours
            total_critical_unserved_kwh += current.loads.unserved_critical_kw * dt_hours
            total_curtailed_kwh += (current.solar.solar_curtailed_kw + current.wind.wind_curtailed_kw) * dt_hours
            total_diesel_generated_kwh += current.diesel.generator_power_kw * dt_hours
            total_fuel_burned_l += current.diesel.fuel_consumption_l_per_h * dt_hours

            if current.resilience:
                ts = current.resilience.threat_state
                threat_state_counts[ts] = threat_state_counts.get(ts, 0) + 1

        summary = {
            "station_id": self.station_id,
            "mode": mode,
            "steps": len(states),
            "duration_hours": len(states) * dt_hours,
            "total_unserved_kwh": round(total_unserved_kwh, 2),
            "total_critical_unserved_kwh": round(total_critical_unserved_kwh, 2),
            "total_curtailed_kwh": round(total_curtailed_kwh, 2),
            "total_diesel_generated_kwh": round(total_diesel_generated_kwh, 2),
            "total_fuel_burned_liters": round(total_fuel_burned_l, 2),
            "final_fuel_remaining_liters": current.fuel.fuel_remaining_l,
            "final_battery_soc": round(current.battery.soc_pct, 4),
            "final_indoor_temp_c": round(current.thermal.indoor_temp_c, 2),
            "threat_state_distribution": threat_state_counts,
            "critical_survival": "PASSED" if total_critical_unserved_kwh < 1e-4 else "FAILED",
            "is_valid": is_valid
        }

        traj = TwinTrajectory(
            station_id=self.station_id,
            mode=mode,
            states=states,
            summary=summary
        )

        return traj, is_valid, validation_messages

