"""
POLARIS-EMS — Feature Engineering Pipeline
SIH26061: Polar Energy Management & Resilience System

Constructs leakage-free feature matrices at forecast origin t for target t+k.
Enforces the strict forecast-origin contract:
- Known-ahead calendar, astronomical, and operational schedules at t+k.
- Causal weather estimates at t+k generated by WeatherForecastProvider.
- Historical telemetry and target lags strictly at or before origin t.
- Backward-looking rolling statistics strictly non-centered at or before t.
"""

from typing import List, Dict, Optional, Tuple
import numpy as np
import pandas as pd

from backend.ml.station_config import StationConfigAdapter
from backend.ml.weather_provider import WeatherForecastProvider, WeatherForecastResult


class FeaturePipeline:
    """Extracts leakage-free feature matrices for load, solar, and wind forecasting."""

    def __init__(self, station_config: Optional[StationConfigAdapter] = None):
        self.station_config = station_config or StationConfigAdapter()
        self.weather_provider = WeatherForecastProvider()

    def extract_features_step(
        self,
        station_id: str,
        target_name: str,
        forecast_origin: pd.Timestamp,
        horizon_k: int,
        history_df: pd.DataFrame,
        known_ahead_row: Optional[pd.Series] = None,
        weather_step: Optional[Dict] = None
    ) -> Dict[str, float]:
        """
        Extracts a single feature vector for predicting target at t + horizon_k from origin t.
        
        Args:
            station_id: BHARATI | MAITRI | HIMADRI
            target_name: total_load_kw | solar_generation_kw | wind_generation_kw
            forecast_origin: Origin timestamp t
            horizon_k: Lead time in hours (>= 1)
            history_df: Telemetry rows strictly <= forecast_origin
            known_ahead_row: Row from schedule/dataset at t+k containing known schedules
            weather_step: Dict of forecast weather at t+k from WeatherForecastProvider
        """
        sid = station_id.upper()
        target_time = forecast_origin + pd.Timedelta(hours=horizon_k)
        
        # 1. Temporal & Cyclical Harmonics (known ahead at t+k)
        hour = target_time.hour
        doy = target_time.dayofyear
        dow = target_time.dayofweek
        
        hour_sin = np.sin(2.0 * np.pi * hour / 24.0)
        hour_cos = np.cos(2.0 * np.pi * hour / 24.0)
        doy_sin = np.sin(2.0 * np.pi * doy / 366.0)
        doy_cos = np.cos(2.0 * np.pi * doy / 366.0)

        # 2. Known-Ahead Operational Schedules at t+k
        if known_ahead_row is not None:
            solar_elev = float(known_ahead_row.get("solar_elevation_deg", 0.0))
            is_daylight = float(solar_elev > 0.0)
            occ_state = float(known_ahead_row.get("occupancy_state", 0.5))
            maint_state = float(known_ahead_row.get("maintenance_state", 0.0))
            res_state = float(known_ahead_row.get("research_activity_state", 0.5))
            comm_state = float(known_ahead_row.get("communication_state", 0.0))
        else:
            solar_elev = 0.0
            is_daylight = 0.0
            occ_state = 0.5
            maint_state = 0.0
            res_state = 0.5
            comm_state = 0.0

        # 3. Causal Weather Forecast at t+k
        if weather_step is not None:
            f_temp = float(weather_step.get("temperature_c", -15.0))
            f_wind = float(weather_step.get("wind_speed_ms", 8.0))
            f_cloud = float(weather_step.get("cloud_fraction", 0.5))
            f_irr = float(weather_step.get("irradiance_wm2", 0.0))
            if "solar_elevation_deg" in weather_step:
                solar_elev = float(weather_step["solar_elevation_deg"])
                is_daylight = float(solar_elev > 0.0)
        else:
            f_temp = -15.0
            f_wind = 8.0
            f_cloud = 0.5
            f_irr = 0.0

        # 4. Historical Telemetry at Origin t (strictly <= t)
        last_row = history_df.iloc[-1]
        orig_temp = float(last_row.get("temperature_c", -15.0))
        orig_wind = float(last_row.get("wind_speed_ms", 8.0))
        orig_irr = float(last_row.get("irradiance_wm2", 0.0))
        orig_press = float(last_row.get("pressure_hpa", 985.0))
        
        # 3-hour barometric delta
        if len(history_df) >= 4:
            press_3h = float(history_df.iloc[-4].get("pressure_hpa", orig_press))
            baro_trend = orig_press - press_3h
        else:
            baro_trend = 0.0

        # 5. Historical Target Lags relative to Origin t (strictly <= t)
        # Check target history series
        target_series = history_df[target_name].values
        n_hist = len(target_series)
        
        def get_lag(step: int) -> float:
            idx = n_hist - 1 - step
            return float(target_series[idx]) if idx >= 0 else float(target_series[0])

        lag_0 = get_lag(0)     # y(t)
        lag_1 = get_lag(1)     # y(t-1)
        lag_2 = get_lag(2)     # y(t-2)
        lag_3 = get_lag(3)     # y(t-3)
        lag_6 = get_lag(6)     # y(t-6)
        lag_12 = get_lag(12)   # y(t-12)
        lag_24 = get_lag(24)   # y(t-24)
        lag_48 = get_lag(48)   # y(t-48)
        lag_168 = get_lag(168) # y(t-168)

        # 6. Backward-looking Rolling Target Stats at Origin t (strictly non-centered)
        def get_rolling_stats(window: int) -> Tuple[float, float, float, float]:
            w = target_series[max(0, n_hist - window):]
            if len(w) == 0:
                return lag_0, 0.0, lag_0, lag_0
            return float(np.mean(w)), float(np.std(w)), float(np.min(w)), float(np.max(w))

        r_mean_3, r_std_3, _, _ = get_rolling_stats(3)
        r_mean_6, r_std_6, _, _ = get_rolling_stats(6)
        r_mean_24, r_std_24, r_min_24, r_max_24 = get_rolling_stats(24)
        r_mean_168, r_std_168, _, _ = get_rolling_stats(168)

        # 7. Physical Envelope Indicators
        therm_params = self.station_config.get_thermal_parameters(sid)
        target_indoor_temp = therm_params["indoor_target_temp_c"]
        thermal_gradient = target_indoor_temp - f_temp
        heating_indicator = max(0.0, 18.0 - f_temp)

        pv_limits = self.station_config.get_solar_limits(sid)
        pv_potential = pv_limits["solar_pv_kw_peak"] * (f_irr / 1000.0)

        wind_limits = self.station_config.get_wind_limits(sid)
        wind_cubic = (f_wind / max(1.0, wind_limits["wind_rated_speed_ms"])) ** 3

        feat_dict = {
            # Harmonics & Calendar
            "horizon_k": float(horizon_k),
            "hour_sin": float(hour_sin),
            "hour_cos": float(hour_cos),
            "doy_sin": float(doy_sin),
            "doy_cos": float(doy_cos),
            "day_of_week": float(dow),
            # Known-Ahead
            "solar_elevation_deg": float(solar_elev),
            "is_daylight": float(is_daylight),
            "occupancy_state": float(occ_state),
            "maintenance_state": float(maint_state),
            "research_activity_state": float(res_state),
            "communication_state": float(comm_state),
            # Causal Weather Forecast
            "forecast_temperature_c": float(f_temp),
            "forecast_wind_speed_ms": float(f_wind),
            "forecast_cloud_fraction": float(f_cloud),
            "forecast_irradiance_wm2": float(f_irr),
            # Origin Telemetry (<= t)
            "origin_temperature_c": float(orig_temp),
            "origin_wind_speed_ms": float(orig_wind),
            "origin_irradiance_wm2": float(orig_irr),
            "origin_pressure_hpa": float(orig_press),
            "barometric_trend_3h": float(baro_trend),
            # Origin Target Lags (<= t)
            "target_lag_0": float(lag_0),
            "target_lag_1": float(lag_1),
            "target_lag_2": float(lag_2),
            "target_lag_3": float(lag_3),
            "target_lag_6": float(lag_6),
            "target_lag_12": float(lag_12),
            "target_lag_24": float(lag_24),
            "target_lag_48": float(lag_48),
            "target_lag_168": float(lag_168),
            # Rolling Statistics at Origin (<= t)
            "rolling_mean_3h": float(r_mean_3),
            "rolling_std_3h": float(r_std_3),
            "rolling_mean_6h": float(r_mean_6),
            "rolling_std_6h": float(r_std_6),
            "rolling_mean_24h": float(r_mean_24),
            "rolling_std_24h": float(r_std_24),
            "rolling_min_24h": float(r_min_24),
            "rolling_max_24h": float(r_max_24),
            "rolling_mean_168h": float(r_mean_168),
            # Physical Drivers
            "thermal_gradient": float(thermal_gradient),
            "heating_demand_indicator": float(heating_indicator),
            "pv_potential_kw": float(pv_potential),
            "wind_cubic_potential": float(wind_cubic),
        }
        return feat_dict

    def build_feature_dataset(
        self,
        station_id: str,
        target_name: str,
        df: pd.DataFrame,
        horizons: List[int],
        min_history_steps: int = 168,
        sample_stride: int = 1,
        mode: str = "CAUSAL"
    ) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
        """
        Builds a multi-horizon feature matrix and target matrix using fast precomputed arrays.
        Enforces the exact same causal contracts with ~100x speedup.
        """
        sid = station_id.upper()
        max_h = max(horizons)
        n_total = len(df)

        # 1. Precompute rolling statistics and barometric trends across the contiguous partition
        target_series = df[target_name]
        r_mean_3 = target_series.rolling(3, min_periods=1).mean().values
        r_std_3 = target_series.rolling(3, min_periods=1).std().fillna(0.0).values
        r_mean_6 = target_series.rolling(6, min_periods=1).mean().values
        r_std_6 = target_series.rolling(6, min_periods=1).std().fillna(0.0).values
        r_mean_24 = target_series.rolling(24, min_periods=1).mean().values
        r_std_24 = target_series.rolling(24, min_periods=1).std().fillna(0.0).values
        r_min_24 = target_series.rolling(24, min_periods=1).min().values
        r_max_24 = target_series.rolling(24, min_periods=1).max().values
        r_mean_168 = target_series.rolling(168, min_periods=1).mean().values
        
        # 3-hour barometric delta
        press_col = df["pressure_hpa"] if "pressure_hpa" in df.columns else pd.Series(985.0, index=df.index)
        baro_trend_3h = (press_col - press_col.shift(3)).fillna(0.0).values

        # 2. Extract column arrays
        timestamps = pd.to_datetime(df["timestamp"], utc=True)
        hours = timestamps.dt.hour.values
        doys = timestamps.dt.dayofyear.values
        dows = timestamps.dt.dayofweek.values

        hour_sins = np.sin(2.0 * np.pi * hours / 24.0)
        hour_coss = np.cos(2.0 * np.pi * hours / 24.0)
        doy_sins = np.sin(2.0 * np.pi * doys / 366.0)
        doy_coss = np.cos(2.0 * np.pi * doys / 366.0)

        targets = target_series.values
        temps = df["temperature_c"].values if "temperature_c" in df.columns else np.full(n_total, -15.0)
        winds = df["wind_speed_ms"].values if "wind_speed_ms" in df.columns else np.full(n_total, 8.0)
        clouds = df["cloud_fraction"].values if "cloud_fraction" in df.columns else np.full(n_total, 0.5)
        irrs = df["irradiance_wm2"].values if "irradiance_wm2" in df.columns else np.zeros(n_total)
        elevs = df["solar_elevation_deg"].values if "solar_elevation_deg" in df.columns else np.zeros(n_total)
        occs = df["occupancy_state"].values if "occupancy_state" in df.columns else np.full(n_total, 0.5)
        maints = df["maintenance_state"].values if "maintenance_state" in df.columns else np.zeros(n_total)
        reses = df["research_activity_state"].values if "research_activity_state" in df.columns else np.full(n_total, 0.5)
        comms = df["communication_state"].values if "communication_state" in df.columns else np.zeros(n_total)
        dists = df["disturbance_state"].values if "disturbance_state" in df.columns else np.array(["NORMAL"] * n_total)

        # Station physics configuration
        therm_params = self.station_config.get_thermal_parameters(sid)
        t_target_indoor = therm_params["indoor_target_temp_c"]
        pv_limits = self.station_config.get_solar_limits(sid)
        pv_peak = pv_limits["solar_pv_kw_peak"]
        wind_limits = self.station_config.get_wind_limits(sid)
        w_rated = max(1.0, wind_limits["wind_rated_speed_ms"])

        clima = self.weather_provider.CLIMATOLOGY.get(sid, {"temp_mean": -12.0, "wind_mean": 9.5, "cloud_mean": 0.45})
        t_clima = clima["temp_mean"]
        w_clima = clima["wind_mean"]
        c_clima = clima["cloud_mean"]

        records_x = []
        records_y = []
        records_meta = []

        # 3. Main feature construction loop
        for origin_idx in range(min_history_steps, n_total - max_h, sample_stride):
            orig_time = timestamps[origin_idx]
            t_orig = temps[origin_idx]
            w_orig = winds[origin_idx]
            c_orig = clouds[origin_idx]
            p_orig = press_col.iloc[origin_idx]
            b_trend = baro_trend_3h[origin_idx]
            irr_orig = irrs[origin_idx]

            # Target lags at origin
            lag_0 = targets[origin_idx]
            lag_1 = targets[origin_idx - 1]
            lag_2 = targets[origin_idx - 2]
            lag_3 = targets[origin_idx - 3]
            lag_6 = targets[origin_idx - 6]
            lag_12 = targets[origin_idx - 12]
            lag_24 = targets[origin_idx - 24]
            lag_48 = targets[origin_idx - 48]
            lag_168 = targets[origin_idx - 168]

            # Rolling stats at origin
            rm_3 = r_mean_3[origin_idx]
            rs_3 = r_std_3[origin_idx]
            rm_6 = r_mean_6[origin_idx]
            rs_6 = r_std_6[origin_idx]
            rm_24 = r_mean_24[origin_idx]
            rs_24 = r_std_24[origin_idx]
            rmin_24 = r_min_24[origin_idx]
            rmax_24 = r_max_24[origin_idx]
            rm_168 = r_mean_168[origin_idx]

            for k in horizons:
                target_idx = origin_idx + k
                t_target_time = timestamps[target_idx]
                y_val = float(targets[target_idx])
                dist_state = str(dists[target_idx])

                # Known-ahead calendar & harmonics at t+k
                h_sin = hour_sins[target_idx]
                h_cos = hour_coss[target_idx]
                d_sin = doy_sins[target_idx]
                d_cos = doy_coss[target_idx]
                dow_val = dows[target_idx]

                s_elev = float(elevs[target_idx])
                is_day = float(s_elev > 0.0)
                occ_val = float(occs[target_idx])
                maint_val = float(maints[target_idx])
                res_val = float(reses[target_idx])
                comm_val = float(comms[target_idx])

                # Causal weather forecast at t+k
                if mode == "ORACLE":
                    f_temp = float(temps[target_idx])
                    f_wind = float(winds[target_idx])
                    f_cloud = float(clouds[target_idx])
                    f_irr = float(irrs[target_idx])
                else:
                    # Fast causal scalar forecast
                    alpha_t = np.exp(-k / 24.0)
                    diurnal_t = 2.5 * np.sin(2.0 * np.pi * (hours[target_idx] - 9) / 24.0)
                    f_temp = alpha_t * t_orig + (1.0 - alpha_t) * t_clima + diurnal_t

                    alpha_w = np.exp(-k / 18.0)
                    storm_boost = max(0.0, -b_trend * 1.5) * np.exp(-k / 12.0)
                    f_wind = max(0.0, alpha_w * w_orig + (1.0 - alpha_w) * w_clima + storm_boost)

                    alpha_c = np.exp(-k / 12.0)
                    f_cloud = float(np.clip(alpha_c * c_orig + (1.0 - alpha_c) * c_clima, 0.0, 1.0))

                    if s_elev > 0.0:
                        air_mass = 1.0 / max(0.05, np.sin(np.radians(s_elev)))
                        i_clear = max(0.0, 1361.0 * np.sin(np.radians(s_elev)) * (0.7 ** (air_mass ** 0.678)))
                        f_irr = float(max(0.0, i_clear * (1.0 - 0.75 * (f_cloud ** 1.5))))
                    else:
                        f_irr = 0.0

                therm_grad = t_target_indoor - f_temp
                heat_ind = max(0.0, 18.0 - f_temp)
                pv_pot = pv_peak * (f_irr / 1000.0)
                wind_cub = (f_wind / w_rated) ** 3

                row = {
                    "horizon_k": float(k),
                    "hour_sin": float(h_sin),
                    "hour_cos": float(h_cos),
                    "doy_sin": float(d_sin),
                    "doy_cos": float(d_cos),
                    "day_of_week": float(dow_val),
                    "solar_elevation_deg": s_elev,
                    "is_daylight": is_day,
                    "occupancy_state": occ_val,
                    "maintenance_state": maint_val,
                    "research_activity_state": res_val,
                    "communication_state": comm_val,
                    "forecast_temperature_c": float(f_temp),
                    "forecast_wind_speed_ms": float(f_wind),
                    "forecast_cloud_fraction": float(f_cloud),
                    "forecast_irradiance_wm2": float(f_irr),
                    "origin_temperature_c": float(t_orig),
                    "origin_wind_speed_ms": float(w_orig),
                    "origin_irradiance_wm2": float(irr_orig),
                    "origin_pressure_hpa": float(p_orig),
                    "barometric_trend_3h": float(b_trend),
                    "target_lag_0": float(lag_0),
                    "target_lag_1": float(lag_1),
                    "target_lag_2": float(lag_2),
                    "target_lag_3": float(lag_3),
                    "target_lag_6": float(lag_6),
                    "target_lag_12": float(lag_12),
                    "target_lag_24": float(lag_24),
                    "target_lag_48": float(lag_48),
                    "target_lag_168": float(lag_168),
                    "rolling_mean_3h": float(rm_3),
                    "rolling_std_3h": float(rs_3),
                    "rolling_mean_6h": float(rm_6),
                    "rolling_std_6h": float(rs_6),
                    "rolling_mean_24h": float(rm_24),
                    "rolling_std_24h": float(rs_24),
                    "rolling_min_24h": float(rmin_24),
                    "rolling_max_24h": float(rmax_24),
                    "rolling_mean_168h": float(rm_168),
                    "thermal_gradient": float(therm_grad),
                    "heating_demand_indicator": float(heat_ind),
                    "pv_potential_kw": float(pv_pot),
                    "wind_cubic_potential": float(wind_cub),
                }
                records_x.append(row)
                records_y.append({"target": y_val})
                records_meta.append({
                    "station_id": sid,
                    "origin_timestamp": orig_time,
                    "target_timestamp": t_target_time,
                    "horizon_k": k,
                    "disturbance_state": dist_state
                })

        return pd.DataFrame.from_records(records_x), pd.DataFrame.from_records(records_y), pd.DataFrame.from_records(records_meta)
