/**
 * POLARIS-EMS — Authoritative Fallback Decision Traces
 * Provides deterministic, verifiable 7-stage decision trace records
 * for Bharati, Maitri, and Himadri research stations.
 * 
 * Epistemic Provenance: SIMULATED / CONFIGURED
 * Used when backend API is starting up or disconnected on localhost.
 */

import { TraceDetail, TraceSummary, DecisionExplanation, DecisionDelta } from '../../api/types';

export const FALLBACK_TRACES: Record<string, { summary: TraceSummary; detail: TraceDetail; explanation: DecisionExplanation }> = {
  BHARATI: {
    summary: {
      decision_trace_id: 'DT-20260927-BHARATI-BASE01',
      station_id: 'BHARATI',
      execution_status: 'COMPLETED',
      creation_timestamp: new Date().toISOString(),
      horizon_hours: 48,
      scenario_id: 'NORMAL_BASELINE',
      optimization_mode: 'EXPECTED',
      primary_directive: 'RENEWABLE_PRIORITY',
      policy_state: 'APPROVED',
      resilience_state: 'SAFE',
      edge_mode: 'CONNECTED_OPERATION',
      event_count: 7,
      terminal_stage: 'POLICY',
      provenance: 'SIMULATED'
    },
    detail: {
      decision_trace_id: 'DT-20260927-BHARATI-BASE01',
      station_id: 'BHARATI',
      execution_status: 'COMPLETED',
      creation_timestamp: new Date().toISOString(),
      horizon_hours: 48,
      scenario_id: 'NORMAL_BASELINE',
      optimization_mode: 'EXPECTED',
      primary_directive: 'RENEWABLE_PRIORITY',
      policy_state: 'APPROVED',
      resilience_state: 'SAFE',
      edge_mode: 'CONNECTED_OPERATION',
      event_count: 7,
      terminal_stage: 'POLICY',
      provenance: 'SIMULATED',
      schema_version: '1.0.0',
      lineage_graph: {
        evt_edge_bh01: ['evt_fc_bh02'],
        evt_fc_bh02: ['evt_sc_bh03'],
        evt_sc_bh03: ['evt_opt_bh04'],
        evt_opt_bh04: ['evt_twin_bh05'],
        evt_twin_bh05: ['evt_res_bh06'],
        evt_res_bh06: ['evt_pol_bh07'],
        evt_pol_bh07: []
      },
      events: [
        {
          event_id: 'evt_edge_bh01',
          trace_id: 'DT-20260927-BHARATI-BASE01',
          stage: 'EDGE',
          event_type: 'EDGE_TELEMETRY_INGEST',
          timestamp: new Date(Date.now() - 360000).toISOString(),
          station_id: 'BHARATI',
          status: 'COMPLETED',
          reason_code: 'TELEMETRY_VERIFIED',
          summary: 'Edge node operating in CONNECTED_OPERATION. 14 device channels sampled with zero stale packets.',
          inputs: { station_id: 'BHARATI', buffer_window_s: 60 },
          outputs: {
            connectivity: 'CONNECTED',
            active_channels: 14,
            data_quality: 'VALID',
            bus_voltage_v: 400.2,
            grid_frequency_hz: 50.02
          },
          validation_tier: 'VALIDATED',
          provenance: 'CONFIGURED',
          parent_event_id: null,
          duration_ms: 12.4,
          engine_version: 'v1.4',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_fc_bh02',
          trace_id: 'DT-20260927-BHARATI-BASE01',
          stage: 'FORECAST',
          event_type: 'ML_INFERENCE_EXECUTION',
          timestamp: new Date(Date.now() - 300000).toISOString(),
          station_id: 'BHARATI',
          status: 'COMPLETED',
          reason_code: 'CONFORMAL_CALIBRATED',
          summary: '48h multi-quantile forecast computed. Solar GHI 185 W/m², katabatic wind 11.4 m/s (P10-P95 conformal interval).',
          inputs: { horizon_hours: 48, model: 'LightGBM_Conformal' },
          outputs: {
            expected_solar_kw: 24.5,
            expected_wind_kw: 13.8,
            temperature_mean_c: -22.4,
            conformal_coverage_pct: 88.5
          },
          validation_tier: 'COMPUTED',
          provenance: 'FORECAST',
          parent_event_id: 'evt_edge_bh01',
          duration_ms: 45.2,
          engine_version: 'v2.1',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_sc_bh03',
          trace_id: 'DT-20260927-BHARATI-BASE01',
          stage: 'SCENARIO',
          event_type: 'STRESS_SCENARIO_EVAL',
          timestamp: new Date(Date.now() - 240000).toISOString(),
          station_id: 'BHARATI',
          status: 'COMPLETED',
          reason_code: 'NOMINAL_STRESS_TOLERANCE',
          summary: 'Evaluated against Katabatic Storm & Generator Trip benchmarks. Reserve margin exceeds 35% safety threshold.',
          inputs: { scenario: 'NORMAL_BASELINE', stress_factor: 1.0 },
          outputs: {
            spinning_reserve_margin_pct: 38.2,
            peak_contingency_deficit_kw: 0.0,
            load_shed_risk: 'NONE'
          },
          validation_tier: 'SIMULATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_fc_bh02',
          duration_ms: 22.1,
          engine_version: 'v1.2',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_opt_bh04',
          trace_id: 'DT-20260927-BHARATI-BASE01',
          stage: 'OPTIMIZER',
          event_type: 'MILP_UNIT_COMMITMENT',
          timestamp: new Date(Date.now() - 180000).toISOString(),
          station_id: 'BHARATI',
          status: 'COMPLETED',
          reason_code: 'SOLVER_OPTIMAL',
          summary: 'HiGHS MILP solver found global optimal unit commitment in 68ms (0.00% optimality gap). DG1 held in standby.',
          inputs: { solver: 'HiGHS', mip_rel_gap: 0.001, horizon_steps: 48 },
          outputs: {
            solver_status: 'optimal',
            solve_time_s: 0.068,
            pv_active_kw: 24.5,
            wind_active_kw: 13.8,
            battery_charge_kw: 8.3,
            diesel_kw: 0.0
          },
          validation_tier: 'COMPUTED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_sc_bh03',
          duration_ms: 68.0,
          engine_version: 'HiGHS-1.5',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_twin_bh05',
          trace_id: 'DT-20260927-BHARATI-BASE01',
          stage: 'TWIN_REPLAY',
          event_type: 'PHYSICS_REPLAY_VALIDATION',
          timestamp: new Date(Date.now() - 120000).toISOString(),
          station_id: 'BHARATI',
          status: 'COMPLETED',
          reason_code: 'KIRCHHOFF_CONSERVED',
          summary: 'Spatial microgrid replayed through thermal and electrochemical equations. Kirchhoff residual < 1e-4 kW.',
          inputs: { steps: 48, conservation_tolerance: 1e-3 },
          outputs: {
            max_kirchhoff_residual_kw: 0.00008,
            battery_soc_terminal_pct: 72.4,
            thermal_zone_comfort_ok: true,
            voltage_drop_max_pct: 1.12
          },
          validation_tier: 'VALIDATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_opt_bh04',
          duration_ms: 38.6,
          engine_version: 'TwinEngine-4.0',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_res_bh06',
          trace_id: 'DT-20260927-BHARATI-BASE01',
          stage: 'RESILIENCE',
          event_type: 'MULTI_DIM_RESILIENCE_CALCULUS',
          timestamp: new Date(Date.now() - 60000).toISOString(),
          station_id: 'BHARATI',
          status: 'COMPLETED',
          reason_code: 'RESILIENCE_SAFE',
          summary: 'Assessed 5 survival dimensions: Energy, Fuel, Thermal, Life Support, Control. Overall resilience index: 0.94.',
          inputs: { horizon_hours: 48, fuel_stock_liters: 42000 },
          outputs: {
            resilience_score: 0.94,
            critical_load_survival_horizon_h: 96.0,
            thermal_decay_hours_to_freezing: 14.5,
            active_threats: 0
          },
          validation_tier: 'ESTIMATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_twin_bh05',
          duration_ms: 18.2,
          engine_version: 'ResilienceCalc-2.0',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_pol_bh07',
          trace_id: 'DT-20260927-BHARATI-BASE01',
          stage: 'POLICY',
          event_type: 'GOVERNANCE_RULE_ENFORCEMENT',
          timestamp: new Date().toISOString(),
          station_id: 'BHARATI',
          status: 'COMPLETED',
          reason_code: 'POL_P1_LIFE_SUPPORT_VERIFIED',
          summary: 'Policy verified: P1 Life Support & P2 Communications 100% supplied. RENEWABLE_PRIORITY directive confirmed.',
          inputs: { active_policy: 'POLAR_NOMINAL_SAFETY' },
          outputs: {
            primary_directive: 'RENEWABLE_PRIORITY',
            policy_state: 'APPROVED',
            p1_served_pct: 100.0,
            p2_served_pct: 100.0,
            operator_action_required: false
          },
          validation_tier: 'VALIDATED',
          provenance: 'CONFIGURED',
          parent_event_id: 'evt_res_bh06',
          duration_ms: 14.1,
          engine_version: 'PolicyEngine-3.2',
          schema_version: '1.0.0',
          diagnostics: []
        }
      ]
    },
    explanation: {
      trace_id: 'DT-20260927-BHARATI-BASE01',
      station_id: 'BHARATI',
      headline: 'Renewable Priority Mode selected: Solar & Wind generation fully satisfy 32 kW connected station demand while buffering battery storage.',
      why_this_state: 'Station electrical bus is stable at 400V 50Hz. All life support heating and mission communication circuits are fully powered with zero shed load.',
      why_this_policy: 'Rule POL_P1 enforces that Life Support circuits receive highest dispatch priority. Current generation provides 118% of required power, permitting renewable priority.',
      why_this_schedule: 'HiGHS MILP optimizer committed 24.5 kW PV and 13.8 kW Wind while storing 8.3 kW surplus in BESS. Diesel generator remained in warm standby, saving 18.2 L fuel.',
      what_data_used: [
        'Edge telemetry from 14 power meters and bus frequency sensors',
        'LightGBM probabilistic solar irradiance and katabatic wind forecasts',
        'Configured Bharati electrical topology and priority rank definitions',
        'Physical battery state-of-charge (SOC: 68%) and thermal heat loss curves'
      ],
      what_was_validated: [
        'Kirchhoff Current Law node conservation across all 5 distribution panels',
        'Bus voltage drop remained within 1.12% (< 3.0% IEEE 1547 polar tolerance)',
        'Thermal comfort levels across Deck 2 habitation modules remained at +20.5°C',
        '35% spinning reserve margin verified against sudden generator outage'
      ],
      what_remains_estimated: [
        'Extended 96h diesel fuel endurance projection assumes nominal consumption curve',
        'Building envelope thermal cooling rate during storm assumes -25°C ambient boundary'
      ],
      what_is_next: 'System will continue in AUTO recommendation posture. Next scheduled MILP re-solve occurs in 60 minutes or immediately if wind speed drops below 4.0 m/s.',
      reason_codes: ['POL_P1_LIFE_SUPPORT_VERIFIED', 'SOLVER_OPTIMAL', 'KIRCHHOFF_CONSERVED', 'CONFORMAL_CALIBRATED']
    }
  },
  MAITRI: {
    summary: {
      decision_trace_id: 'DT-20260927-MAITRI-BASE01',
      station_id: 'MAITRI',
      execution_status: 'COMPLETED',
      creation_timestamp: new Date().toISOString(),
      horizon_hours: 48,
      scenario_id: 'NORMAL_BASELINE',
      optimization_mode: 'EXPECTED',
      primary_directive: 'THERMAL_PROTECTION',
      policy_state: 'APPROVED',
      resilience_state: 'SAFE',
      edge_mode: 'CONNECTED_OPERATION',
      event_count: 7,
      terminal_stage: 'POLICY',
      provenance: 'SIMULATED'
    },
    detail: {
      decision_trace_id: 'DT-20260927-MAITRI-BASE01',
      station_id: 'MAITRI',
      execution_status: 'COMPLETED',
      creation_timestamp: new Date().toISOString(),
      horizon_hours: 48,
      scenario_id: 'NORMAL_BASELINE',
      optimization_mode: 'EXPECTED',
      primary_directive: 'THERMAL_PROTECTION',
      policy_state: 'APPROVED',
      resilience_state: 'SAFE',
      edge_mode: 'CONNECTED_OPERATION',
      event_count: 7,
      terminal_stage: 'POLICY',
      provenance: 'SIMULATED',
      schema_version: '1.0.0',
      lineage_graph: {
        evt_edge_mt01: ['evt_fc_mt02'],
        evt_fc_mt02: ['evt_sc_mt03'],
        evt_sc_mt03: ['evt_opt_mt04'],
        evt_opt_mt04: ['evt_twin_mt05'],
        evt_twin_mt05: ['evt_res_mt06'],
        evt_res_mt06: ['evt_pol_mt07'],
        evt_pol_mt07: []
      },
      events: [
        {
          event_id: 'evt_edge_mt01',
          trace_id: 'DT-20260927-MAITRI-BASE01',
          stage: 'EDGE',
          event_type: 'EDGE_TELEMETRY_INGEST',
          timestamp: new Date(Date.now() - 360000).toISOString(),
          station_id: 'MAITRI',
          status: 'COMPLETED',
          reason_code: 'TELEMETRY_VERIFIED',
          summary: 'Edge node operating in CONNECTED_OPERATION. Water trace heating and boiler loop monitors active.',
          inputs: { station_id: 'MAITRI', buffer_window_s: 60 },
          outputs: { connectivity: 'CONNECTED', active_channels: 12, water_line_temp_c: 4.2 },
          validation_tier: 'VALIDATED',
          provenance: 'CONFIGURED',
          parent_event_id: null,
          duration_ms: 11.2,
          engine_version: 'v1.4',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_fc_mt02',
          trace_id: 'DT-20260927-MAITRI-BASE01',
          stage: 'FORECAST',
          event_type: 'ML_INFERENCE_EXECUTION',
          timestamp: new Date(Date.now() - 300000).toISOString(),
          station_id: 'MAITRI',
          status: 'COMPLETED',
          reason_code: 'CONFORMAL_CALIBRATED',
          summary: 'Oasis weather forecast: solar GHI 160 W/m², moderate wind 9.2 m/s, overnight drop to -18°C.',
          inputs: { horizon_hours: 48, model: 'LightGBM_Conformal' },
          outputs: { expected_solar_kw: 14.2, expected_wind_kw: 9.8, temperature_mean_c: -16.5 },
          validation_tier: 'COMPUTED',
          provenance: 'FORECAST',
          parent_event_id: 'evt_edge_mt01',
          duration_ms: 42.1,
          engine_version: 'v2.1',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_sc_mt03',
          trace_id: 'DT-20260927-MAITRI-BASE01',
          stage: 'SCENARIO',
          event_type: 'STRESS_SCENARIO_EVAL',
          timestamp: new Date(Date.now() - 240000).toISOString(),
          station_id: 'MAITRI',
          status: 'COMPLETED',
          reason_code: 'NOMINAL_STRESS_TOLERANCE',
          summary: 'Evaluated Priyadarshini water pipeline freeze-protection margin. Minimum electric trace heating: 8.5 kW.',
          inputs: { scenario: 'NORMAL_BASELINE' },
          outputs: { pipe_freeze_risk: 'LOW', trace_heat_load_kw: 8.5 },
          validation_tier: 'SIMULATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_fc_mt02',
          duration_ms: 19.8,
          engine_version: 'v1.2',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_opt_mt04',
          trace_id: 'DT-20260927-MAITRI-BASE01',
          stage: 'OPTIMIZER',
          event_type: 'MILP_UNIT_COMMITMENT',
          timestamp: new Date(Date.now() - 180000).toISOString(),
          station_id: 'MAITRI',
          status: 'COMPLETED',
          reason_code: 'SOLVER_OPTIMAL',
          summary: 'HiGHS MILP dispatched DG1 at 35 kW base load with BESS buffering lake pump transients.',
          inputs: { solver: 'HiGHS' },
          outputs: { diesel_kw: 35.0, battery_kw: -5.2, pv_kw: 14.2, wind_kw: 9.8 },
          validation_tier: 'COMPUTED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_sc_mt03',
          duration_ms: 61.2,
          engine_version: 'HiGHS-1.5',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_twin_mt05',
          trace_id: 'DT-20260927-MAITRI-BASE01',
          stage: 'TWIN_REPLAY',
          event_type: 'PHYSICS_REPLAY_VALIDATION',
          timestamp: new Date(Date.now() - 120000).toISOString(),
          station_id: 'MAITRI',
          status: 'COMPLETED',
          reason_code: 'KIRCHHOFF_CONSERVED',
          summary: 'Living Blocks A and B central spine heating validated. Residual < 1e-4 kW.',
          inputs: { steps: 48 },
          outputs: { max_kirchhoff_residual_kw: 0.00007, pipe_freeze_margin_h: 8.2 },
          validation_tier: 'VALIDATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_opt_mt04',
          duration_ms: 36.4,
          engine_version: 'TwinEngine-4.0',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_res_mt06',
          trace_id: 'DT-20260927-MAITRI-BASE01',
          stage: 'RESILIENCE',
          event_type: 'MULTI_DIM_RESILIENCE_CALCULUS',
          timestamp: new Date(Date.now() - 60000).toISOString(),
          station_id: 'MAITRI',
          status: 'COMPLETED',
          reason_code: 'RESILIENCE_SAFE',
          summary: 'Multi-dimension resilience index: 0.91. Fuel reserve: 78 days at current dispatch.',
          inputs: { horizon_hours: 48 },
          outputs: { resilience_score: 0.91, critical_load_survival_horizon_h: 82.0 },
          validation_tier: 'ESTIMATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_twin_mt05',
          duration_ms: 17.5,
          engine_version: 'ResilienceCalc-2.0',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_pol_mt07',
          trace_id: 'DT-20260927-MAITRI-BASE01',
          stage: 'POLICY',
          event_type: 'GOVERNANCE_RULE_ENFORCEMENT',
          timestamp: new Date().toISOString(),
          station_id: 'MAITRI',
          status: 'COMPLETED',
          reason_code: 'POL_P1_LIFE_SUPPORT_VERIFIED',
          summary: 'Directive THERMAL_PROTECTION confirmed. Water supply line and habitat heating fully protected.',
          inputs: { active_policy: 'MAITRI_THERMAL_PRESERVATION' },
          outputs: { primary_directive: 'THERMAL_PROTECTION', policy_state: 'APPROVED' },
          validation_tier: 'VALIDATED',
          provenance: 'CONFIGURED',
          parent_event_id: 'evt_res_mt06',
          duration_ms: 13.5,
          engine_version: 'PolicyEngine-3.2',
          schema_version: '1.0.0',
          diagnostics: []
        }
      ]
    },
    explanation: {
      trace_id: 'DT-20260927-MAITRI-BASE01',
      station_id: 'MAITRI',
      headline: 'Thermal Protection Mode: Central heating corridor and Priyadarshini water pumps given strict priority dispatch.',
      why_this_state: 'Oasis overnight freeze threatens surface water intake pipes. Trace heating and boiler circuits are operating at 100% capacity.',
      why_this_policy: 'Maitri rulebook prioritizes thermal survivability to prevent irreversible freezing of domestic freshwater pipes.',
      why_this_schedule: 'DG1 committed to steady 35 kW baseline with BESS absorbing sudden heating pump load swings.',
      what_data_used: ['Priyadarshini water line temperature sensors', 'Oasis boundary ambient temperature', 'Cummins generator telemetry'],
      what_was_validated: ['Zero pipeline freezing risk under -18°C night chill', 'Bus voltage regulation within 1.4%'],
      what_remains_estimated: ['Long-term water line heat loss rate under 40-knot katabatic gusting'],
      what_is_next: 'Monitoring lake pumphouse current draw; auto-modulating electric heaters as ambient temperature shifts.',
      reason_codes: ['MAITRI_THERMAL_PRESERVATION', 'SOLVER_OPTIMAL', 'PIPE_FREEZE_SAFE']
    }
  },
  HIMADRI: {
    summary: {
      decision_trace_id: 'DT-20260927-HIMADRI-BASE01',
      station_id: 'HIMADRI',
      execution_status: 'COMPLETED',
      creation_timestamp: new Date().toISOString(),
      horizon_hours: 48,
      scenario_id: 'NORMAL_BASELINE',
      optimization_mode: 'EXPECTED',
      primary_directive: 'SETTLEMENT_GRID_OPTIMAL',
      policy_state: 'APPROVED',
      resilience_state: 'SAFE',
      edge_mode: 'CONNECTED_OPERATION',
      event_count: 7,
      terminal_stage: 'POLICY',
      provenance: 'SIMULATED'
    },
    detail: {
      decision_trace_id: 'DT-20260927-HIMADRI-BASE01',
      station_id: 'HIMADRI',
      execution_status: 'COMPLETED',
      creation_timestamp: new Date().toISOString(),
      horizon_hours: 48,
      scenario_id: 'NORMAL_BASELINE',
      optimization_mode: 'EXPECTED',
      primary_directive: 'SETTLEMENT_GRID_OPTIMAL',
      policy_state: 'APPROVED',
      resilience_state: 'SAFE',
      edge_mode: 'CONNECTED_OPERATION',
      event_count: 7,
      terminal_stage: 'POLICY',
      provenance: 'SIMULATED',
      schema_version: '1.0.0',
      lineage_graph: {
        evt_edge_hm01: ['evt_fc_hm02'],
        evt_fc_hm02: ['evt_sc_hm03'],
        evt_sc_hm03: ['evt_opt_hm04'],
        evt_opt_hm04: ['evt_twin_hm05'],
        evt_twin_hm05: ['evt_res_hm06'],
        evt_res_hm06: ['evt_pol_hm07'],
        evt_pol_hm07: []
      },
      events: [
        {
          event_id: 'evt_edge_hm01',
          trace_id: 'DT-20260927-HIMADRI-BASE01',
          stage: 'EDGE',
          event_type: 'EDGE_TELEMETRY_INGEST',
          timestamp: new Date(Date.now() - 360000).toISOString(),
          station_id: 'HIMADRI',
          status: 'COMPLETED',
          reason_code: 'TELEMETRY_VERIFIED',
          summary: 'Settlement microgrid feeder monitored. District grid frequency at 50.01 Hz.',
          inputs: { station_id: 'HIMADRI' },
          outputs: { connectivity: 'CONNECTED', grid_intertie_status: 'ACTIVE', active_channels: 10 },
          validation_tier: 'VALIDATED',
          provenance: 'CONFIGURED',
          parent_event_id: null,
          duration_ms: 9.8,
          engine_version: 'v1.4',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_fc_hm02',
          trace_id: 'DT-20260927-HIMADRI-BASE01',
          stage: 'FORECAST',
          event_type: 'ML_INFERENCE_EXECUTION',
          timestamp: new Date(Date.now() - 300000).toISOString(),
          station_id: 'HIMADRI',
          status: 'COMPLETED',
          reason_code: 'CONFORMAL_CALIBRATED',
          summary: 'Ny-Ålesund Arctic summer forecast: 24h daylight solar irradiance 145 W/m².',
          inputs: { horizon_hours: 48 },
          outputs: { expected_solar_kw: 11.2, expected_wind_kw: 0.0, temperature_mean_c: -4.2 },
          validation_tier: 'COMPUTED',
          provenance: 'FORECAST',
          parent_event_id: 'evt_edge_hm01',
          duration_ms: 38.4,
          engine_version: 'v2.1',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_sc_hm03',
          trace_id: 'DT-20260927-HIMADRI-BASE01',
          stage: 'SCENARIO',
          event_type: 'STRESS_SCENARIO_EVAL',
          timestamp: new Date(Date.now() - 240000).toISOString(),
          station_id: 'HIMADRI',
          status: 'COMPLETED',
          reason_code: 'NOMINAL_STRESS_TOLERANCE',
          summary: 'Interconnection stability evaluated. Station BESS capable of 4h islanded operation.',
          inputs: { scenario: 'NORMAL_BASELINE' },
          outputs: { islanding_reserve_h: 4.2 },
          validation_tier: 'SIMULATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_fc_hm02',
          duration_ms: 16.4,
          engine_version: 'v1.2',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_opt_hm04',
          trace_id: 'DT-20260927-HIMADRI-BASE01',
          stage: 'OPTIMIZER',
          event_type: 'MILP_UNIT_COMMITMENT',
          timestamp: new Date(Date.now() - 180000).toISOString(),
          station_id: 'HIMADRI',
          status: 'COMPLETED',
          reason_code: 'SOLVER_OPTIMAL',
          summary: 'Optimized settlement grid import (18.5 kW) plus rooftop solar (11.2 kW).',
          inputs: { solver: 'HiGHS' },
          outputs: { grid_import_kw: 18.5, pv_kw: 11.2, battery_kw: 0.0 },
          validation_tier: 'COMPUTED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_sc_hm03',
          duration_ms: 54.2,
          engine_version: 'HiGHS-1.5',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_twin_hm05',
          trace_id: 'DT-20260927-HIMADRI-BASE01',
          stage: 'TWIN_REPLAY',
          event_type: 'PHYSICS_REPLAY_VALIDATION',
          timestamp: new Date(Date.now() - 120000).toISOString(),
          station_id: 'HIMADRI',
          status: 'COMPLETED',
          reason_code: 'KIRCHHOFF_CONSERVED',
          summary: 'Ground wet labs and upper crew berths power flows validated.',
          inputs: { steps: 48 },
          outputs: { max_kirchhoff_residual_kw: 0.00005, sample_freezer_temp_c: -80.1 },
          validation_tier: 'VALIDATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_opt_hm04',
          duration_ms: 31.0,
          engine_version: 'TwinEngine-4.0',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_res_hm06',
          trace_id: 'DT-20260927-HIMADRI-BASE01',
          stage: 'RESILIENCE',
          event_type: 'MULTI_DIM_RESILIENCE_CALCULUS',
          timestamp: new Date(Date.now() - 60000).toISOString(),
          station_id: 'HIMADRI',
          status: 'COMPLETED',
          reason_code: 'RESILIENCE_SAFE',
          summary: 'Resilience index: 0.96. Settlement grid connection active with local BESS backup.',
          inputs: { horizon_hours: 48 },
          outputs: { resilience_score: 0.96, critical_load_survival_horizon_h: 120.0 },
          validation_tier: 'ESTIMATED',
          provenance: 'SIMULATED',
          parent_event_id: 'evt_twin_hm05',
          duration_ms: 15.2,
          engine_version: 'ResilienceCalc-2.0',
          schema_version: '1.0.0',
          diagnostics: []
        },
        {
          event_id: 'evt_pol_hm07',
          trace_id: 'DT-20260927-HIMADRI-BASE01',
          stage: 'POLICY',
          event_type: 'GOVERNANCE_RULE_ENFORCEMENT',
          timestamp: new Date().toISOString(),
          station_id: 'HIMADRI',
          status: 'COMPLETED',
          reason_code: 'POL_P1_LIFE_SUPPORT_VERIFIED',
          summary: 'SETTLEMENT_GRID_OPTIMAL directive active. Sample freezers and research telemetry protected.',
          inputs: { active_policy: 'NY_ALESUND_SETTLEMENT_POLICY' },
          outputs: { primary_directive: 'SETTLEMENT_GRID_OPTIMAL', policy_state: 'APPROVED' },
          validation_tier: 'VALIDATED',
          provenance: 'CONFIGURED',
          parent_event_id: 'evt_res_hm06',
          duration_ms: 12.1,
          engine_version: 'PolicyEngine-3.2',
          schema_version: '1.0.0',
          diagnostics: []
        }
      ]
    },
    explanation: {
      trace_id: 'DT-20260927-HIMADRI-BASE01',
      station_id: 'HIMADRI',
      headline: 'Settlement Grid Optimization: Blending 11.2 kW continuous Arctic solar with Ny-Ålesund district power.',
      why_this_state: 'Station electrical bus is interconnected with Kings Bay microgrid. Clean power conditioners protect scientific sample deep-freezers.',
      why_this_policy: 'Himadri operates within international environmental covenants prioritizing grid efficiency and quiet RF operation.',
      why_this_schedule: 'Station BESS remains at 85% standby charge to provide seamless uninterrupted power in case of settlement feeder maintenance.',
      what_data_used: ['Ny-Ålesund grid feeder meters', '24h Arctic solar irradiance sensors', 'Scientific instrument telemetry'],
      what_was_validated: ['Deep-freezer temperatures stable at -80°C', 'Harmonic distortion on scientific bus < 1.8%'],
      what_remains_estimated: ['Settlement centralized heating fuel reserve for coming winter season'],
      what_is_next: 'Normal monitoring. Routine battery float charge maintained.',
      reason_codes: ['NY_ALESUND_SETTLEMENT_POLICY', 'GRID_INTERTIE_ACTIVE', 'SOLVER_OPTIMAL']
    }
  }
};

export function computeDecisionDelta(t1: TraceDetail, t2: TraceDetail): DecisionDelta {
  const t1Opt = t1.events.find(e => e.stage === 'OPTIMIZER')?.outputs || {};
  const t2Opt = t2.events.find(e => e.stage === 'OPTIMIZER')?.outputs || {};
  const t1Res = t1.events.find(e => e.stage === 'RESILIENCE')?.outputs || {};
  const t2Res = t2.events.find(e => e.stage === 'RESILIENCE')?.outputs || {};

  return {
    base_trace_id: t1.decision_trace_id,
    compare_trace_id: t2.decision_trace_id,
    station_id: t1.station_id,
    policy_directive_changed: t1.primary_directive !== t2.primary_directive,
    edge_mode_changed: t1.edge_mode !== t2.edge_mode,
    summary_narrative: `Comparative delta between ${t1.decision_trace_id} (${t1.execution_status}) and ${t2.decision_trace_id} (${t2.execution_status}). Shows operational state transitions and generator/battery dispatch variations.`,
    state_transitions: {
      'Execution Status': [t1.execution_status, t2.execution_status],
      'Policy State': [t1.policy_state || 'NOMINAL', t2.policy_state || 'NOMINAL'],
      'Resilience State': [t1.resilience_state || 'SAFE', t2.resilience_state || 'SAFE'],
      'Primary Directive': [t1.primary_directive || 'NONE', t2.primary_directive || 'NONE'],
      'Optimization Mode': [t1.optimization_mode, t2.optimization_mode]
    },
    numerical_deltas: {
      'Diesel Power (kW)': Number((((t2Opt.diesel_kw as number) || 0) - ((t1Opt.diesel_kw as number) || 0)).toFixed(2)),
      'Solar Power (kW)': Number((((t2Opt.pv_active_kw as number || t2Opt.pv_kw as number) || 0) - ((t1Opt.pv_active_kw as number || t1Opt.pv_kw as number) || 0)).toFixed(2)),
      'Wind Power (kW)': Number((((t2Opt.wind_active_kw as number || t2Opt.wind_kw as number) || 0) - ((t1Opt.wind_active_kw as number || t1Opt.wind_kw as number) || 0)).toFixed(2)),
      'Resilience Score': Number((((t2Res.resilience_score as number) || 0.92) - ((t1Res.resilience_score as number) || 0.92)).toFixed(3)),
      'Event Count': t2.event_count - t1.event_count
    }
  };
}
