"""
POLARIS-EMS — Data Provenance Contract
SIH26061: Polar Energy Management & Resilience System

Enforces strict classification of every energy and weather value in the system:
- REAL: Sourced directly from verified meteorological sources (NCPOR AWS, ERA5 reanalysis).
- CONFIGURED: Stated engineering specifications, asset ratings, and manufacturer parameters.
- ASSUMED: Well-defined engineering approximations (e.g., building heat loss coefficients).
- SYNTHETIC: Generated by the physics/operational synthetic environment.
- FORECAST: Machine learning predictions with calibrated uncertainty intervals.
- SIMULATED: Future state transitions computed by the Energy Digital Twin or Optimizer.
"""

from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field
from datetime import datetime, timezone


class ProvenanceTier(str, Enum):
    REAL = "REAL"
    CONFIGURED = "CONFIGURED"
    ASSUMED = "ASSUMED"
    SYNTHETIC = "SYNTHETIC"
    FORECAST = "FORECAST"
    SIMULATED = "SIMULATED"


class ProvenanceRecord(BaseModel):
    """Metadata tag attached to any value or dataset to guarantee transparency."""
    tier: ProvenanceTier = Field(..., description="Classification tier")
    source: str = Field(..., description="Origin of the data (e.g., 'NCPOR_AWS_Maitri', 'PhysicsGenerator_v1', 'XGBoost_P50')")
    description: str = Field("", description="Contextual note on data collection or calculation")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="UTC timestamp of tagging")
    is_verified: bool = Field(False, description="Whether the data source has been verified against ground-truth registry")


class ProvenanceMetric(BaseModel):
    """Generic wrapper for any scalar metric carrying explicit provenance."""
    metric_name: str
    value: float
    unit: str
    provenance: ProvenanceRecord

    def summary(self) -> str:
        return f"[{self.provenance.tier.value}] {self.metric_name}: {self.value:.2f} {self.unit} (Source: {self.provenance.source})"
