"""
backend/edge/adapters/emulator_adapter.py
"""
"""EmulatorAdapter – a concrete DeviceAdapter for software emulation of devices.

All telemetry generated by this adapter is marked ``SIMULATED`` provenance and
includes ``environment=EMULATOR`` metadata. No real hardware is required.
"""

from typing import List, Dict, Any
from datetime import datetime, timezone

from backend.edge.adapters.base_adapter import DeviceAdapter
from backend.edge.schema import DeviceProfile, DeviceType, DeviceHealthState, ConnectivityState, DeviceChannelConfig


class EmulatorAdapter(DeviceAdapter):
    def __init__(self, source: str = "default") -> None:
        self._source = source

    @property
    def environment(self) -> str:
        return "EMULATOR"

    @property
    def source(self) -> str:
        return self._source

    def discover_devices(self) -> List[DeviceProfile]:
        return [DeviceProfile(
            device_id="emu-gen-001", station_id="EMULATOR_STATION",
            device_type=DeviceType.DIESEL_GENERATOR, name="Emulated Generator",
            rated_capacity=4000.0, unit="kW", provenance="SIMULATED",
            telemetry_channels=[DeviceChannelConfig(channel="power", unit="kW", min_val=0.0, max_val=4500.0)],
            source_metadata={"environment": self.environment, "source": self.source},
        )]

    def read_telemetry(self, device_id: str) -> List[Dict[str, Any]]:
        if device_id != "emu-gen-001":
            raise KeyError(f"Device '{device_id}' not found in emulator.")
        return [{"station_id": "EMULATOR_STATION", "device_id": device_id, "channel": "power",
                 "timestamp": datetime.now(timezone.utc).isoformat(), "value": 2000.0,
                 "unit": "kW", "quality": "VALID", "provenance": "SIMULATED", "source": "emulator"}]

    def write_actuation(self, device_id: str, command: Dict[str, Any]) -> Dict[str, Any]:
        if device_id != "emu-gen-001":
            raise KeyError(f"Device '{device_id}' not found in emulator.")
        return {"device_id": device_id, "status": "SIMULATED", "command": command,
                "environment": self.environment, "source": self.source}
